# Generated by Django 4.2.2 on 2023-06-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoGas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula_digital', models.CharField(default='', max_length=100)),
                ('nombre_del_proyecto', models.CharField(default='', max_length=100, unique=True)),
                ('escenario', models.CharField(default='', max_length=100)),
                ('empresa', models.CharField(default='', max_length=100)),
                ('segmento', models.CharField(default='', max_length=100)),
                ('subsegmento', models.CharField(default='', max_length=100)),
                ('unidad_de_negocios_regional', models.CharField(default='', max_length=100)),
                ('gerencia', models.CharField(default='', max_length=100)),
                ('activo', models.CharField(default='', max_length=100)),
                ('departamento', models.CharField(default='', max_length=100)),
                ('categoria', models.CharField(default='', max_length=100)),
                ('subcategoria', models.CharField(default='', max_length=100)),
                ('fase_actual', models.CharField(default='', max_length=100)),
                ('riesgo', models.CharField(default='', max_length=100)),
                ('dimension', models.CharField(default='', max_length=100)),
                ('ejecutor', models.CharField(default='', max_length=100)),
                ('variante', models.CharField(default='', max_length=100)),
                ('proxima_toma_de_decision', models.DateField(null=True)),
                ('fecha_fid', models.DateField(null=True)),
                ('gas', models.IntegerField(null=True)),
                ('seguimiento', models.CharField(default='', max_length=100)),
                ('palanca_tecnologica', models.CharField(default='', max_length=100)),
                ('cuenca_venture', models.CharField(default='', max_length=100)),
                ('hidrocarburo', models.CharField(default='', max_length=100)),
                ('recobro', models.CharField(default='', max_length=100)),
                ('capex_transicion', models.IntegerField(null=True)),
                ('vpn_musd', models.IntegerField(null=True)),
                ('e_vpn_musd', models.IntegerField(null=True)),
                ('efi_veces', models.IntegerField(null=True)),
                ('tir', models.IntegerField(null=True)),
                ('parback_meses', models.IntegerField(null=True)),
                ('be_crudo', models.IntegerField(null=True)),
                ('be_gas', models.IntegerField(null=True)),
                ('capex_unitario', models.IntegerField(null=True)),
                ('first_oil_gas', models.IntegerField(null=True)),
                ('volumenes_1p', models.IntegerField(null=True)),
                ('volumenes_2p', models.IntegerField(null=True)),
                ('volumenes_3p', models.IntegerField(null=True)),
                ('recursos_contigentes', models.IntegerField(null=True)),
                ('rec_desc_delimitar_verificar', models.IntegerField(null=True)),
                ('recursos_prospectivos', models.IntegerField(null=True)),
            ],
        ),
    ]
