# Generated by Django 4.2.2 on 2023-07-07 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField(null=True)),
                ('valor', models.IntegerField(null=0)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gas.proyectogas', to_field='nombre_del_proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Prod_Inc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField(null=True)),
                ('valor', models.FloatField(default=0)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gas.proyectogas', to_field='nombre_del_proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Pozos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField(null=True)),
                ('cantidad', models.IntegerField(null=0)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gas.proyectogas', to_field='nombre_del_proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Operaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField(null=True)),
                ('total', models.FloatField(default=0)),
                ('contingencia', models.FloatField(default=0)),
                ('capex', models.FloatField(default=0)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gas.proyectogas', to_field='nombre_del_proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Inversiones_MUSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(default='Enero', max_length=20)),
                ('año', models.IntegerField(null=True)),
                ('monto', models.FloatField(default=0)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gas.proyectogas', to_field='nombre_del_proyecto')),
            ],
        ),
    ]
