# Generated by Django 4.2.2 on 2023-06-08 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoRenovable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnologia', models.CharField(max_length=100)),
                ('nombre_del_proyecto', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('esquema_de_negocio', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('ecopetrol_filial', models.CharField(max_length=100)),
                ('vicep_filial', models.CharField(max_length=100)),
                ('activo', models.CharField(max_length=100)),
                ('riesgo_materializacion', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('lider_iniciativa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Monto_PID_MMUSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renovables.proyectorenovable')),
            ],
        ),
    ]
