# Generated by Django 4.2.1 on 2023-06-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renovables', '0002_proyectorenovable_capacidad_instalada_mw_mwp_dc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monto_pid_mmusd',
            name='año',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monto_pid_mmusd',
            name='monto',
            field=models.FloatField(default=0),
        ),
    ]
