# Generated by Django 4.2.2 on 2023-06-22 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renovables', '0003_monto_pid_mmusd_año_monto_pid_mmusd_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monto_pid_mmusd',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renovables.proyectorenovable'),
        ),
        migrations.CreateModel(
            name='MW_Incorporadas_por_ano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.DateField(blank=True, null=True)),
                ('montomw', models.FloatField(default=0)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renovables.proyectorenovable')),
            ],
        ),
    ]
